### ISSUE TITLE
Read accuracy vs. empirical accuracy

### ISSUE THREAD

**Issue by krdav** [jbloomlab/alignparse#102]
Thanks for the code. Lots of useful stuff like the functions parsing cs-tags.

You define ccs accuracy as Avg(Phred score over the feature). As per:
https://github.com/jbloomlab/alignparse/blob/972f0051fe8ea5f905aae0b85b43de22478f9c1c/alignparse/utils.py#L165

But then you calculate empirical accuracy (if I understand correctly) as epsilon = the probability of seeing any error in the feature. Isn't this an apples-to-orchard comparison? And wouldn't you rather want to report the ccs accuracy as Prod(Phred score over the feature) to make it comparable to the empirical accuracy?
At least that makes more sense to me if you want to do an explicit comparison, as in the recA DMS example:
https://jbloomlab.github.io/alignparse/recA_DMS.html

**Comment by jbloom** [comment]
The `qvals_to_accuracy` just reports the estimated per-site error rate from the Q values reported by the CCS program. If I recall correctly, this is because some versions of `pbccs` (the PacBio program) also reports a similar "accuracy" value. This number is independent of the length of the thing being sequenced, and who knows how accurate it is because I'm not sure how quantitatively reflective the Q-values are always of the true sequencing accuracy (although they are certainly correlated).

In contrast, the empirical accuracy is just a measure of how often multiple CCSs for what should be the same amplicon give the same sequence. This will be influenced by the underlying sequencing accuracy, the length of the amplicon, and any other factors that might introduce errors (PCR, library prep, etc).

So I agree that these are different things, and to compare them you would minimally need to adjust the `qvals_to_accuracy` value by the length of the amplicon as well.

**Comment by krdav** [comment]
Good, then I understand it correctly.
Yes, the ccs program probably classify reads based on average quals ≥Q20 and then calls them HiFi.
And yes, I also suspect the Q-values could be off, particularly if the reads have some small amount of heteroduplexes e.g. in DMS libraries, or with UMIs, if the strands are denatured and reannealing causes heteroduplexes.

But anyhow, thanks for the clarification.
