### ISSUE TITLE
add hyperlinks to API in example notebooks

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/alignparse#42]
Right now the notebooks refer to `alignparse` functions like `Targets`, but those are not hyperlinked to the actual API documentation.

We want them to be hyperlinked. For instance, look at the [dms_variants examples](https://jbloomlab.github.io/dms_variants/codonvariant_sim_data.html): when it refers to `CodonVariantTable` that is actually hyperlinked like this [CodonVariantTable](https://jbloomlab.github.io/dms_variants/dms_variants.codonvarianttable.html#dms_variants.codonvarianttable.CodonVariantTable).

Now that you have built an initial draft of the `gh-pages` docs, you can go back and hyperlink key references to the API in all three notebooks. For instance, what you currently have represented as `Targets` would now by hyperlinked in the Jupyter notebook Markdown like this [Targets](https://jbloomlab.github.io/alignparse/alignparse.targets.html#alignparse.targets.Targets).

You can get the exact hyperlinks for classes / methods / functions from the [index here](https://jbloomlab.github.io/alignparse/genindex.html).

**Comment by khdusenbury** [comment]
I think I added all the hyperlinks. 

The only think I didn't hyperlink were references to `feature_parse_specs` because these references are more references to the user-defined file, not the function (which just turns the file into a dict), so hyperlinking to the documentation didn't seem to make much sense. Let me know if you think I should though or if you see any hyperlinks I missed.

**Comment by jbloom** [comment]
@khdusenbury When you're done editing docs, do you just want to re-build `gh-pages` off of the updated `docs` and I can look at that and see if anything seems missing.

**Comment by khdusenbury** [comment]
Ah yes, that will be the easiest. Will do.

**Comment by jbloom** [comment]
This looks good to me.
